using Microsoft.Bot.Builder.Middleware;
using Microsoft.Bot.Schema;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SupportBot.Messages
{
    public class ChatBotRequest
    {
        public ChatBotRequest(IActivity activity, Intent topIntent, IEnumerable<IActivity> responses)
        {
            UserRequest = activity;
            TopIntent = topIntent;
            Responses = responses;
        }

        /// <summary>
        /// Gets the original incoming request
        /// </summary>
        public IActivity UserRequest { get; }

        /// <summary>
        /// Gets the intent that was detected by LUIS
        /// </summary>
        public Intent TopIntent { get; }

        /// <summary>
        /// Gets the responses generated by Q&A maker or similar middleware.
        /// </summary>
        public IEnumerable<IActivity> Responses { get; }
    }
}
